<?xml version="1.0" encoding="UTF-8"?>

<entity-mappings xmlns="http://xmlns.jcp.org/xml/ns/persistence/orm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.2" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence/orm
http://xmlns.jcp.org/xml/ns/persistence/orm_2_2.xsd">
  <package>$package$</package>
  $NamedQueries:NamedQuery(); separator="\n"$
  $NamedNativeQueries:NamedNativeQuery(); separator="\n"$
  $SqlResultSetMappings:SqlResultSetMapping(); separator="\n"$
</entity-mappings>